[WEAV-199] 팀 초대 링크 생성 API
Student-Center/weave-server pull request #113
Opened 2024-02-18 08:16 UTC by wonjunYou

## Background

- 미팅 팀 초대 기능

![image](https://github.com/Student-Center/weave-server/assets/59856002/997b09a0-12a1-4dcd-9082-d33bc5b95afc)

## **Methodology & Design(Proposal)**

### Goals

- 미팅 팀 초대 기능을 구현합니다.
    - 초대 링크를 생성하여 팀원을 초대할 수 있어야 합니다.
        - 초대 링크 생성은 **팀장만 가능합니다.**
        - 초대 링크의 만료 기한은 1일입니다.

### API

- **초대 링크 생성**
    - POST */api/meeting-teams/{meetingTeamId}/invitation*
        - request
            - method & path: `POST */api/meeting-teams/{meetingTeamId}/invitation*`
            - body
                
                ```json
                --
                ```
                
        
        - response
            - 정상 처리된 경우
                - status code: `200 OK`
                - body
                    
                    ```jsx
                    {
                        "teamId" : "3fa85f64-5717-4562-b3fc-2c963f66afa6", // uuid,
                        "invitationCode" : "as142304-5717-4562-b3fc-2c963f66afa6" // uuid
                    }
                    ```
                    
                    - teamId : 초대 코드를 생성한 팀의 id 값
                    - code : 초대 코드

### 구현 세부사항
* 초대 링크는 랜덤 UUID값을 사용합니다.
* 생성한 링크를 RDB 대신 Redis에 따로 저장하도록 구현하였습니다.
* 초대 링크의 TTL은 임시로 생성 후 1일로 설정하였습니다.

2024-02-18 08:34 UTC, wonjunYou commented
테스트 깨지는 것 수정중입니다!

2024-02-18 08:44 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/api/MeetingTeamApi.kt
> -import com.studentcenter.weave.bootstrap.meetingTeam.dto.MeetingTeamGetMyResponse
p4) import 아스트릭 문자(`*`) 사용을 지양해주세요
@waterfogSW

2024-02-18 08:44 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
> +import com.studentcenter.weave.application.meetingTeam.port.inbound.*
p4) 이렇게 되면 밑에 import 다 지워져야할 것 같아요. 하지만 지양합시다

2024-02-18 08:44 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
> +        }
p4) 동일한 scope funciton을 여러 쓰는건 가독성이 좋진 않을 것 같아요!
```suggestion
        return meetingTeamCreateInvitationUseCase.invoke(
        	MeetingTeamCreateInvitationUseCase.Command(meetingTeamId = meetingTeamId)
        ).let {
            MeetingTeamCreateInvitationResponse(
                teamId = it.teamId,
                invitationCode = it.invitationCode
            )
        }
```

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamCreateInvitationUseCase.kt
> +    )
p4) 핵심 도메인의 식별자만 들어온다면 command 안쓰기?!

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamCreateInvitationUseCase.kt
> +        val teamId: UUID,
p3) 요건 요청자가 주는 값 중 하나인데 응답에 필요한지 모르겠어요!

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamInvitationRepository.kt
> +    fun save(
p4) 줄바꿈
```suggestion
interface MeetingTeamInvitationRepository {

    fun save(
```

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamInvitationRepository.kt
> +        expirationSeconds: Long,
p3) 소요시간을 표현할 때 Duration이 좋을 것 같아요
```suggestion
        expirationDuration: Duration,
```

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamInvitationRepository.kt
> +    ): UUID
p3) command라면 응답 지양
```suggestion
    )
```

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +        )
p2) id만 활용한다면 별도로 유저 조회가 필요하지 않을 것 같아요.

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +        )
p3) 파라미터로 userId를 받는 것이 메서드 표현에 더 적절할 것 같아요

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +        }
p4) 리더 멤버를 조회해서 id를 비교하는 것보다 자신의 멤버 정보를 가져와서 Role 체크하는게 더 좋은 방향일 것 같아요. 
필요에 따라 자신의 멤버정보는 외부에서 조회해서 재활용될 수도 있어서요!

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +        }
p3) 이부분은 팀의 상태도 함께 체크되어야 할 것 같아요! publish인지?

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +        val invitationCode = UUID.randomUUID()
p4) 내부 오브젝트 사용하기?
```suggestion
        val invitationCode = UuidCreator.create()
```

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/resources/application-application.yaml
> +      expire-seconds: ${INVITATION_EXPIRE_SECONDS:86400}
p3) 1시간 정도만 해도 될 것 같은데 어떰?

2024-02-18 08:44 UTC, dojinyou commented on application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/util/impl/MeetingTeamInvitationServiceImplTest.kt
> +            actual::class shouldBe UUID::class
p3) 위에서 클래스를 명시적으로 not null의 uuid를 선언하고 있어서 이 검증은 크게 의미 없어보임!
오히려 초대코드가 잘 저장되어 있는지 repo 체크하는게 좋아보임

2024-02-18 08:44 UTC, dojinyou commented on application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamInvitationRepositorySpy.kt
> +    override fun save(
```suggestion
    private val bucket = ConcurrentHashMap<UUID, UUID>()

    override fun save(
```

2024-02-18 08:44 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamCreateInvitationUseCase.kt
> +        val invitationCode: UUID,
p3) 필요하면 InvitationCode VO나 Data class로 래핑해도될듯

2024-02-18 08:44 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/controller/MeetingTeamRestController.kt
>      ) {
p4) lint
```suggestion
    ) {
```

2024-02-18 09:19 UTC, waterfogSW commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meetingTeam/dto/MeetingTeamCreateInvitationResponse.kt
> +)
p5) 이거 굳이 띄울 필요 있나요? 자동 린트에서 동작한건 아닌거같은데,

2024-02-18 09:19 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationServiceTest.kt
> +                )
p3) UserAuthenticationFixtureFactory가 존재해요

2024-02-18 09:19 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +            expirationSeconds = meetingTeamInvitationProperties.expireSeconds,
p3) 이건 VO로 만들어버려도 될 것 같은데, 어떻게 생각하시나요?

2024-02-18 09:19 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationServiceTest.kt
> +                )
p4) 반복되는것같은데, 줄일수 있는 방법은 없을까요?

2024-02-18 09:19 UTC, waterfogSW commented on application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/MeetingTeamInvitationPropertiesFixtureFactory.kt
> +            expireSeconds: Long = 86400
p4) 매직넘버?

2024-02-18 09:19 UTC, waterfogSW commented on infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/meetingTeam/adapter/MeetingTeamInvitationRedisAdapter.kt
> +
p4) 
```suggestion
```

이거 혹시 자동린트에서 동작하는건가요? 메서드 구현 앞뒤로 엔터가 있는것같은데

2024-02-18 09:19 UTC, waterfogSW commented on infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/meetingTeam/adapter/MeetingTeamInvitationRedisAdapter.kt
> +
p4) 
```suggestion
```

2024-02-18 10:22 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamInvitationRepository.kt
> +    ): UUID
리턴값이 필요해서 command 사용하지 않도록 변경했습니다!

2024-02-18 10:28 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +        )
요건 생각 못했네요 굿굿

2024-02-18 10:58 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +        val invitationCode = UUID.randomUUID()
미리 만들어두신 게 있었군요!

2024-02-18 11:04 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/inbound/MeetingTeamCreateInvitationUseCase.kt
> +        val invitationCode: UUID,
음 그냥 랜덤한 UUID라서 VO까지는 안 가도 될 것 같아요! 자체 검증할 것도 없고..

2024-02-18 11:08 UTC, wonjunYou commented on application/src/main/resources/application-application.yaml
> +      expire-seconds: ${INVITATION_EXPIRE_SECONDS:86400}
조금 긴 것 같기도 해요..ㅎ 1시간으로 하고 한번 모니터링 해보죠!!

2024-02-18 11:16 UTC, wonjunYou commented on application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/util/impl/MeetingTeamInvitationServiceImplTest.kt
> +            actual::class shouldBe UUID::class
맞아요 아직 조회로직 짜기 전이라 이렇게 두었습니다 추가 반영할게요!

2024-02-18 12:08 UTC, wonjunYou commented on infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/meetingTeam/adapter/MeetingTeamInvitationRedisAdapter.kt
> +
kotlin에 설정을 안해뒀던 걸로..ㅠ 전체 코드 리포매팅 한번 할게요!

2024-02-18 13:00 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +            expirationSeconds = meetingTeamInvitationProperties.expireSeconds,
좋은 생각인데요?!

2024-02-18 13:33 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamInvitationRepository.kt
> +    ): UUID
요기선 딱히 받을 거 없을 것 같은데!

2024-02-18 13:36 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/port/outbound/MeetingTeamInvitationRepository.kt
> +    ): UUID
아아 어차피 초대 코드 생성은 domain service에서 하니까 굳이 repository 이후로 반환값을 만들지 말라는 말씀이신가요??

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +        return meetingMemberRepository.findAllByMeetingTeamId(meetingTeam.id).size < meetingTeam.memberCount
p4) 필요하면 count 메서드를 만드는게 좋을지도? 커버링 인덱스 처리 될듯

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +    }
굳이 메서드 안 뺴도 될듯?

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +            )
p4) 쿼리 날라가는 메서드보다 안 날라가는 걸 먼저 체크해도 좋을듯?

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +        )
p3) save의 반환값을 반환하지말고 invitationCode를 반환하는게 좋아보임.
왜냐하면 지금 직관적으로 보면 teamId가 key값이라 해당 값도 동일한 UUID 타입이기 때문에 식별자가 반환된다고 보는게 일반적이라 invitationCode가 반환될 것이라고 생각 안할 수 있음!

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingTeamInvitation.kt
> +}
p3) 줄바꿈 설정도 추가하길
```suggestion
}

```

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/vo/MeetingTeamInvitation.kt
> +    val expirationDuration: Long,
p3) Duration이라고 변수명을 지으면 Duration Type을 쓰라는 의미

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +        else nickname.substring(0, Nickname.MAX_LENGTH)
p3) 뭔가 이상하게 바뀐 것 같은데 줄 바꿈은 일반적으로 2 들여쓰기임

2024-02-18 13:48 UTC, dojinyou commented on application/src/main/resources/application-application.yaml
> +      expire-duration: ${INVITATION_EXPIRE_SECONDS:3600}
여기 Seconds로 표기해주는게 맞음!

2024-02-18 13:48 UTC, dojinyou commented on application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/MeetingTeamInvitationPropertiesFixtureFactory.kt
> +        private const val EXPIRE_DURATION = 3600L
```suggestion
        private const val DEFAULT_EXPIRE_DURATION = 3600L
```

2024-02-18 13:59 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +        )
이해했습니다!

2024-02-18 14:00 UTC, waterfogSW reviewed
구현 설명에는 초대 링크 생성을 구현한다고 하셨는데, 구현은 invitationCode만 있어서 추가 설명가능할까요?

2024-02-18 14:00 UTC, waterfogSW commented on application/src/testFixtures/kotlin/com/studentcenter/weave/application/meetingTeam/outbound/MeetingTeamInvitationRepositorySpy.kt
> +    ): UUID {
p3) 파라미터 한개라도 띄우는게 컨벤션으로 적용되어있나요?

2024-02-18 14:39 UTC, wonjunYou commented
> 구현 설명에는 초대 링크 생성을 구현한다고 하셨는데, 응답으로는
> 
> ```json
>     "teamId" : "3fa85f64-5717-4562-b3fc-2c963f66afa6", // uuid,
>     "invitationCode" : "as142304-5717-4562-b3fc-2c963f66afa6" // uuid
> ```
> 
> 두값이 나오는걸로 되어있는데, 링크 생성이 아니라 초대 코드 생성인것 같아요. 이 값이 링크 구현에 어떻게 활용되는지 설명해주실수 있나요?

요거 일단 teamId는 제외하기로 했고, 클라분과 논의 결과 저기에 저희 서버쪽 도메인만 붙여서 최종적으로 링크 형태로 반환하도록 수정할 것 같아요!!

2024-02-18 14:44 UTC, waterfogSW commented
> 요거 일단 teamId는 응답값에서 제외하기로 했고, 클라분과 논의 결과 저기에 저희 서버쪽 도메인만 붙여서 최종적으로 링크 형태로 반환하도록 수정할 것 같아요!!

그럼 아직 개발진행중인건가요? 수정될부분 리뷰하게 될수도 있으니 draft로 바꾸어주심이 좋을듯해요 😄

2024-02-18 15:03 UTC, wonjunYou commented
> 그럼 아직 개발진행중인건가요? 그렇다면 수정될부분 리뷰하게 될수도 있으니 draft로 바꾸어주심이 좋을듯해요 😄

네네 사실 그 부분만 추가하면 됩니다!! 일단 draft로 바꿔둘게요 :)
꼼꼼한 리뷰 감사드립니다!!

2024-02-19 15:45 UTC, waterfogSW requested changes
리베이스가 잘 안된것 같아요, 이전 PR이랑 겹치는 내용들이 올라와있네요, 수정되면 다시 리뷰할게요!

2024-02-19 15:45 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +    private val meetingMemberRepository: MeetingMemberRepository,
p2) applicationService에서는 repository직접 참조하기보다는 domain거치는게 좋을듯해요

2024-02-19 15:45 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationServiceTest.kt
> +        }
p3) describe 블럭에 두신 이유가 있을까요? 🤔

2024-02-20 05:12 UTC, wonjunYou commented on application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationServiceTest.kt
> +        }
위치 이동했습니다!!

2024-02-20 05:12 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +    private val meetingMemberRepository: MeetingMemberRepository,
수정할게요 :)

2024-02-20 05:57 UTC, waterfogSW requested changes

2024-02-20 05:57 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamCreateInvitationApplicationService.kt
> +                )
p3) 굳이 validate로 어떤 validation이 일어나는지 숨길 필요는 없을것 같아요

2024-02-20 05:57 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/domain/impl/MeetingTeamDomainServiceImpl.kt
> +
p1) 이건 현재 PR에서 수정사항으로 나오면 안되는 내용인데, update가 안된것같네요, 수정되면 다시 리뷰할게요

2024-02-20 14:48 UTC, closed without merging