[WEAV-254] 초대 코드 미팅팀 조회 API
Student-Center/weave-server pull request #129
Opened 2024-02-25 01:24 UTC by wonjunYou

## 작업 내용

![image](https://github.com/Student-Center/weave-server/assets/59856002/0d028bf0-5e11-4b2e-93ea-63363ed48db9)

* 초대 링크를 통해 접속한 유저에 대해, 팀 초대 수락 가능 여부를 판별하기 위한 조회 API입니다.
* 초대 코드를 이용하여 미팅팀을 조회합니다.

## API

- GET */api/meeting-teams/invitation/{invitationCode}*
    - response
        - 정상 처리된 경우
            - status code: `200 OK`
            
            - body
            ```javascript
               {
                    "teamId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", // uuid
                    "teamIntroduce" : "string",
	                "status" : "MeetingTeamStatus" // WAITING
               }
            ```

## 고민 사항 
* 쿼리 파라미터 URL 내의 특수문자가 Swagger에서 테스팅 시 자동으로 인코딩되는 문제가 있습니다. 
* `Invalid URI: [The encoded slash character is not allowed]`

![image](https://github.com/Student-Center/weave-server/assets/59856002/fdcc2878-34e0-49b9-b085-7ea1cba1950b)

* `ApplicationServiceTest` 에서 초대 링크를 생성해서 조회하는 것까지 모두 통과했지만, Swagger를 통해 테스팅이 어려운 상태입니다. 해당 이슈 해결을 위해 추가 설정이나 개발이 필요할까요?(ex. 필터 추가 or swagger 자체 설정파일 추가 등)
* 클라이언트 측에서 요청 보낼 때 관련 설정이 가능한 것으로 파악하고 있어요🤔

### 해결
* 피드백 주신 대로, 링크를 그대로 사용하지 않고 **초대 코드를 통해 조회하는 방향**으로 수정 완료했습니다!

2024-02-25 01:57 UTC, waterfogSW reviewed
링크를 쿼리파라미터로 받지말고, 임의의 코드를 쿼리파라미터로 받아 처리하도록 하면 안되나요? (UUID라던지)

2024-02-25 01:57 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationLinkApplicationService.kt
> +            meetingTeamInvitationService.getByInvitationLink(invitationLink = invitationLink)
p3) getBy인데, nullalbe 값을 반환하는게 어색해요
p4) 타입 명시하는게 리뷰하는 입장에서는 좋은것 같네요!

2024-02-25 01:57 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationLinkApplicationServiceTest.kt
> +    }
p3) mockk를 사용하면 clearAllMocks로 목 해제해주는게 좋을것 같아요

2024-02-25 02:48 UTC, dojinyou requested changes

2024-02-25 02:48 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/common/exception/MeetingTeamExceptionType.kt
> +    INVITATION_LINK_NOT_FOUND("MEETING-TEAM-003"),
p2) LINK는 접속의 수단이지 인증의 수단이 아닌 것 같아요.
LINK에 같이 나가는 CODE를 이용하는게 좋을 것 같아요

2024-02-25 03:22 UTC, wonjunYou commented
code로 조회하도록 수정해야겠군요!! draft로 바꾸고 작업하겠습니다

2024-02-25 03:26 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationLinkApplicationService.kt
> +            meetingTeamInvitationService.getByInvitationLink(invitationLink = invitationLink)
> p3) getBy인데, nullalbe 값을 반환하는게 어색해요 

findBy~ 이런 느낌이 더 적합하겠네요!

> p4) 타입 명시하는게 리뷰하는 입장에서는 좋은것 같네요!

짚어주셔서 감사합니다!

2024-02-25 07:50 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationLinkApplicationService.kt
> +            meetingTeamInvitationService.getByInvitationLink(invitationLink = invitationLink)
@waterfogSW get보다는 find가 좀 더 문맥상 찾아본다는 느낌이 들어서 말씀드렸어요!!

2024-02-25 07:54 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationLinkApplicationService.kt
> +            meetingTeamInvitationService.getByInvitationLink(invitationLink = invitationLink)
https://szymonkrajewski.pl/the-practical-difference-between-findby-and-getby-in-repositories/

2024-02-25 08:34 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationLinkApplicationService.kt
> +            meetingTeamInvitationService.getByInvitationLink(invitationLink = invitationLink)
헉 이것도 암묵적인 컨벤션인건가요..?? 또 하나 배워갑니다..ㅎ

2024-02-25 10:38 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
>      }
p4) chaining사용하면 더 가독성이 좋을것 같네요

2024-02-25 10:38 UTC, waterfogSW commented on infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/meetingTeam/entity/MeetingTeamInvitationRedisHash.kt
> +
p3) JPA에서는 nullable로 처리했을때 매핑이 안되는 문제가 있어서 value class대신 primitive 타입을 사용했어서요, 애플리케이션 외에 외부 인프라 레이어에서는 primitive 타입을 사용하는걸로 통일하면 어떨까요?

2024-02-25 10:38 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationCodeApplicationService.kt
> +    }
p3) 사용자가 초대 코드가 존재하지 않습니다 라는 응답을 받으면 어떻게 대처해야할지 알 수 없을것 같아요

2024-02-25 10:40 UTC, waterfogSW reviewed
초대받은팀에 자리가 없는경우를 확인하는 플로우는 코드 상에 확인 되지 않는데, 어떻게 진행되나요?

2024-02-25 14:21 UTC, wonjunYou commented on infrastructure/redis/src/main/kotlin/com/studentcenter/weave/infrastructure/redis/meetingTeam/entity/MeetingTeamInvitationRedisHash.kt
> +
아 그렇네요! 미처 생각지도 못했습니다😊😊
그럼 어댑터쪽에서 string으로 convert하면 되겠네요!

2024-02-25 14:22 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationCodeApplicationService.kt
> +    }
좀 더 사용자 친화적으로 적어볼게요!

2024-02-25 14:29 UTC, wonjunYou commented
> 초대받은팀에 자리가 없는경우를 확인하는 플로우는 코드 상에 확인 되지 않는데, 어떻게 진행되나요?

이거 저도 고민했던 포인트였어요. 일단은 현재 조회 로직에서는 `status` 를 받아서 판단하는 방향으로 생각했습니다. 

1. 초대 api의 플로우가 링크를 타고 들어온 사용자는 우선 해당 초대 링크(코드)를 통해 팀명, 참여 가능 여부를 먼저 체킹해요.
- PR 내 왼쪽 사진의 모달창에서 해당 조회 로직이 사용됩니다.

2. 수락하기를 눌렀을 때 입장 요청 API가 날라가면 이때 실제 팀에 자리가 있는지 체킹하는 로직을 포함시키려고 합니다.

그 이유는 첫 모달창에서 초대장을 수락하지 않는 경우도 있을 수 있고, 결국은 실제 입장할 때에도 체킹이 진행되어야 하기 때문입니다!

2024-02-25 15:41 UTC, waterfogSW approved these changes

2024-02-25 15:55 UTC, dojinyou approved these changes

2024-02-25 15:55 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationCodeApplicationService.kt
> +            .let { return meetingTeamDomainService.getById(it.teamId) }
p4) `?.let` 활용하는게 조금 더 코틀린스러운 것 같아요.
p4) 만료인지 원래 없는 코드인지 알 수 없기 때문에 문구를 바꿔야할 것 같아요!
```suggestion
       return meetingTeamInvitationService.findByInvitationCode(invitationCode = invitationCode)?.let {
           meetingTeamDomainService.getById(it.teamId)
       } ?: throw CustomException(
           type = MeetingTeamExceptionType.INVITATION_CODE_NOT_FOUND,
           message = "초대 링크를 찾을 수 없어요! 초대링크를 확인해주세요!"
       )
```

2024-02-25 15:55 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationCodeApplicationService.kt
> +    private fun validateInvitationCodeExists(meetingTeamInvitation: MeetingTeamInvitation?): MeetingTeamInvitation {
p3) validate에서 반환값이 있는게 어색해요!

2024-02-25 15:55 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +        }
p4) `apply`와 `also`는 모두 컨텍스트 객체를 반환해서 문제는 없지만, 보통 `apply`는 객체 자체의 변경을, `also`는 추가적인 행위를 할 때 사용해요. 여기서 `also`가 더 적절한 것 같아요
```suggestion
        ).also {
            meetingTeamInvitationRepository.save(it)
        }
```

2024-02-26 00:39 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/service/application/MeetingTeamGetByInvitationCodeApplicationService.kt
> +            .let { return meetingTeamDomainService.getById(it.teamId) }
좋습니다! 다만 초대링크를 확인해 달라고 하면 사용자 입장에서는 어떻게 해야 할 지 애매하다고 생각해서 아래와 같이 수정할게요!

>  message = "초대 링크를 찾을 수 없어요! 초대링크를 확인해주세요!"

message = "초대 링크를 찾을 수 없어요! 새로운 초대 링크를 통해 입장해 주세요!"

2024-02-26 00:41 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meetingTeam/util/impl/MeetingTeamInvitationServiceImpl.kt
> +        }
좋은 지적 감사합니다!!

2024-02-26 01:02 UTC, merged