[WEAV-278] 디스코드 이벤트 WEB HOOK 구현
Student-Center/weave-server pull request #206
Opened 2024-03-20 12:33 UTC by wonjunYou

2024-03-20 14:11 UTC, dojinyou requested changes
환경별로 발송여부가 결정되거나 달라야할 것 같아요!
ex) 개발서버는 이벤트 발송을 하지 않거나 특정 다른 채널(개발서버용)으로 보내기!, 실서버는 발송등!

2024-03-20 14:11 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
> +        val userCount = userDomainService.countAll()
p3) 코루틴 스코프 안에서 호출하면 안되나요?

2024-03-20 14:11 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
> +        )
p3) 굳이 메서드로 빼는 이유가 있나요?

2024-03-20 14:28 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
> +        val userCount = userDomainService.countAll()
스코프 안에서 처리하면 user register 커밋 이전에 count가 되더라고요! (ex. 3번째인데 2번째로 표기됨)
정합성이 안 맞아서 밖으로 분리했습니다!

2024-03-20 14:29 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
> +        )
요 로직이 유저 등록 비즈니스 로직이랑 같이 한 트랜잭션 내에서 안 타게 하려고 했어요..! AOP에서 함수 내부 호출에 대해서는 트랜잭션 적용이 안 된다는 점을 이용했어요!

2024-03-20 14:30 UTC, wonjunYou commented
환경별 프로파일 분리를 잊었네요! 작업해두겠습니다 !!

2024-03-20 14:31 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationServiceTest.kt
> +                }
p3) 이부분 port mocking도 좋지만 stub으로 처리해도 좋을거같아요 (UserGetMyProfileApplicationService에 79Line 참조)

2024-03-20 14:33 UTC, waterfogSW commented on infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/user/adaptor/UserEventDiscordAdaptor.kt
> +            )
p3) 여기서 CustomException던지면 예외처리는 어디서 되나요?

2024-03-20 14:38 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
> +        val userCount = userDomainService.countAll()
트랜잭션은 어노테이션 말고 템플릿으로 스코프 잡고 가는게 좋아보여요

2024-03-21 00:51 UTC, wonjunYou commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationServiceTest.kt
> +                }
에러는 상태 검증이니 stubbing이 좀 더 적합하겠군요!

2024-03-21 02:01 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationService.kt
> +        )
코루틴 스코프 내에 있는것도 트랜잭션 적용을 받나요?

2024-03-21 14:29 UTC, waterfogSW commented on infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/user/adaptor/UserEventDiscordAdaptor.kt
> +            )
coroutine exception handler만드신다는 뜻일까요

2024-03-21 14:31 UTC, wonjunYou commented on infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/user/adaptor/UserEventDiscordAdaptor.kt
> +            )
음.. 어떻게 처리하면 좋을까요??

2024-03-21 14:50 UTC, dojinyou commented on infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/discord/user/adaptor/UserEventDiscordAdaptor.kt
> +            )
지금처럼 FireAndForgot 패턴이라면 에러 반환하지말고 로그만 남기고 작업 끝내는게 좋을 것 같아요.

2024-03-25 00:16 UTC, waterfogSW requested changes

2024-03-25 00:16 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
> +    fun meetingUpdateIfNeeded(
p2) private 이 왜 빠진건가요?
p3) 어떤상황에서 왜 이걸쓰는건지 메서드명이나 코드로는 잘 파악이 안되는것 같아요.

2024-03-25 00:16 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserRegisterApplicationServiceTest.kt
> +
p2) 클래스 전역에 이렇게 두기보다는 해당하는 테스트에만 stub을 적용하는게 좋을것 같아요

2024-03-25 00:16 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingEventPort.kt
> +        receivingMeetingTeamMbti: Mbti,
p4) 인자가 너무많은것 같아요

2024-03-25 02:28 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
> +    fun meetingUpdateIfNeeded(
앗 private을 지워 버렸군요.. 수정하겠습니다!

2024-03-25 02:29 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
> +    fun meetingUpdateIfNeeded(
좀 더 명확하게 변경 해볼게요!

2024-03-25 13:47 UTC, dojinyou approved these changes

2024-03-26 04:46 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meeting/port/outbound/MeetingEventPort.kt
> +        meetingMatchingInfo: MeetingMatchingInfo,
좋습니다!

2024-03-26 04:49 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/meeting/service/application/MeetingAttendanceCreateApplicationService.kt
> +        updateMeetingIfNeeded(
요거 미팅 멤버들의 미팅 참여 의사에 따라서 ex. 미팅 참여 취소(1명이라도 캔슬 시), 미팅 전원 참석 시에 따라 업데이트가 필요하면 한다는 의미인 것 같아요!

2024-03-26 04:49 UTC, wonjunYou commented on infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/common/event/ClientEventType.kt
> +enum class ClientEventType {
제거하겠습니다 !

2024-03-26 07:31 UTC, waterfogSW commented on infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/common/event/ClientEventType.kt
> +enum class ClientEventType {
아 그냥 여쭤본거였어요.. 필요하다면 붙어있는게 맞는데, 
UserEventType, MeetingEventType이런식으로 가도 되고, 아니면 UserRegisterEvent, MeetingMatchedEvent 요런식으로 DTO를 나눠도 될것같아요

2024-03-26 07:32 UTC, waterfogSW commented on infrastructure/client/src/main/kotlin/com/studentcenter/weave/infrastructure/client/common/event/ClientEventType.kt
> +enum class ClientEventType {
근데 discord쪽에서 처리하는 내용이라 DiscordMesaageType으로 바꾸는게 좋을까요?

2024-03-26 07:33 UTC, waterfogSW approved these changes

2024-03-26 07:39 UTC, merged