[WEAV-321] 채팅, 채팅방 도메인 개발
Student-Center/weave-server pull request #229
Opened 2024-04-01 07:22 UTC by waterfogSW

2024-04-01 07:24 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/ChatMessage.kt
> +)
약속잡기, 이미지 전송 등등 여러종류의 메시지 종류 상속해 구현

2024-04-01 09:28 UTC, dojinyou requested changes

2024-04-01 09:28 UTC, dojinyou commented on application/src/test/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessageTest.kt
> +                exception.message shouldBe "1000자 이내로 입력해 주세요!"
p4) 메세지 검증은 개인적으로 안해도 된다고 생각해요! 너무 잘 바뀔 수 있는 부분이라 관리포인트가 늘어나는 것 같아서요!

2024-04-01 09:28 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/ChatRoom.kt
> +) {
p2) 미팅 id도 알고 있어야 할 것 같아요! 정확히는 미팅 id는 무조건 알아야하고 편의를 위해서 팀 id까지 넣어주는 느낌?

2024-04-01 09:28 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
p3) Sender 정보까지는 필수 같은데 ChatMeesage에 올리는 건 어떨까요? 
고민되는 포인트는 유저가 아니라 공지나 봇 같은 객체가 메세지 보내는 것도 잘 표현할 수 있는 구조면 좋겠다 싶네요!

2024-04-01 10:17 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
네네 사실 그부분때문에 TextMessage로 sendUserId를 빼버렸는데요, chatMessage로 올리게 되면, 공지나 봇같은 객체는 별도로 User로 만들어서 처리해야하는지? 아니면 null로 해야하는지? null로 한다면 사용사례가 대부분 user이기도 하고 null이 봇이 보낸거다 라는걸 명세한다기에는 좀 약한것같아서 고민이었어요. 

그래서 차라리 봇이나 공지의 경우에는 TextMessage가 아니라 별도의 객체를 만들어서 처리하는게 좋겠다 생각했어요

2024-04-02 04:27 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
제 생각에는 메세지는 메세지고 보내는 사람에 따라서 바뀌면 안되는 것 같아요!
Sender에 대한 정보를 ChatMessage에서 가지고 있고, TextMessage와 같이 구현체는 content에 대해서 잘 표현하면 좋을 것 같은데 어떤가요? 제가 예상하는 ChatMessage로서 필수요소에는 Sender에 대한 정보(type, id와 같은) 것들이 포함되어서 상위 객체가 맞는것 같아요!

2024-04-02 06:16 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
음 그러면 User와는 다른 별도의 Sender라는 객체를 만들어야 할까요? ChatMessage에 Sender에 대한 정보를 포함하려고 하면, User의 정보인지, 봇의 정보인지 판단하기가 어려울것 같아서요.

차라리 TextMessage를 UserTextMessage라고 하고, User정보를 UserTextMessage가 갖게 하는건 어떨까요?

2024-04-02 06:20 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
Sender 정보 판단이 어려운 이유를 잘 모르겠어요!! `SenderType / SenderId` 정도로 생각했었어요

2024-04-02 06:24 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
SenderType을 사용한다면 가능할것 같은데, type이라는 별도의 속성을 두는게 최선일지, Sender를 상속한 SendUser, SendBot 같은걸 만드는게 좋을지 잘모르겠네요

2024-04-02 06:28 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
송신자 정보를 표현하는 방법으로는 크게 두 가지 옵션이 있을 것 같아요

1. ChatMessage에 senderType과 senderId 필드를 추가하는 방법
```kotlin
abstract class ChatMessage(
    open val id: UUID = UuidCreator.create(),
    open val roomId: UUID,  
    open val senderType: SenderType,
    open val senderId: UUID,
    open val createdAt: LocalDateTime = LocalDateTime.now(),
)

enum class SenderType {
    USER, BOT, NOTICE
}
```
2. Sender 인터페이스를 만들고 이를 구현한 UserSender, BotSender 등의 클래스를 사용하는 방법
```kotlin
abstract class ChatMessage(
    open val id: UUID = UuidCreator.create(),  
    open val roomId: UUID,
    open val sender: Sender,
    open val createdAt: LocalDateTime = LocalDateTime.now(),  
)

interface Sender
data class UserSender(val userId: UUID) : Sender  
data class BotSender(val botId: UUID) : Sender
object NoticeSender : Sender
```

개인적으로는 2번 방법이 객체지향 설계 관점에서 더 깔끔하고 확장성이 좋아보여요. Sender를 인터페이스로 정의하면 향후 새로운 유형의 송신자가 추가되더라도 ChatMessage를 수정할 필요없이 Sender 인터페이스를 구현하는 새로운 클래스만 만들면 되기 때문에 괜찮은 방법인듯함니다

2024-04-02 06:30 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
저는 2번으로 가져가고 Sender가 ChatMessagㄷ에 들어가면 된다고 생각했어요! DB에 저장할 때는 Type으로 데이터 만들어주고요!

2024-04-02 07:16 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
```mermaid
classDiagram
direction BT
class ChatRoom {
   +UUID id
   +UUID meetingId
   +UUID receivingTeamId
   +UUID requestingTeamId
   +LocalDateTime createdAt
   +UserTextMessage sendUserTextMessage(UUID sendUserId, String content)
   +ChatRoom create(Meeting meeting)
}
class UserTextMessage {
   +UUID roomId
   +SendUser sender
   +String content
   +UserTextMessage create(UUID roomId, UUID sendUserId, String content)
}
class SendUser {
   +UUID userId
}
class ChatMessage {
   <<abstract>>
   +UUID id
   +UUID roomId
   +Sender sender
   +LocalDateTime createdAt
}
class Sender {
   <<interface>>
}

ChatRoom ..> UserTextMessage : creates
UserTextMessage --|> ChatMessage
SendUser ..|> Sender
UserTextMessage *-- SendUser
ChatMessage o-- Sender
```

2024-04-02 07:37 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
ChatMessage의 Sender랑 UserTextMessage의 SenderUser랑 겹치는거 같아요.

2024-04-02 08:07 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/chat/entity/TextMessage.kt
> +    val sendUserId: UUID,
겹친다는게 어떤뜻일까요? 상속관계라..

2024-04-02 15:25 UTC, dojinyou approved these changes

2024-04-02 23:20 UTC, merged