[WEAV-169] 회원 키설정 API 구현
Student-Center/weave-server pull request #56
Opened 2024-02-04 14:51 UTC by waterfogSW

## 구현 사항
- 회원 키설정 API 구현이에요

2024-02-04 15:31 UTC, dojinyou requested changes

2024-02-04 15:31 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
> +            avatar = avatar,
p2) 명시적으로 null을 넣는 경우와 값을 안 바꾸고 싶은 경우를 구분하기 어려울 것 같아요

2024-02-05 01:20 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
> +            avatar = avatar,
한번 wrapping해서 null로 업데이트 하는 경우를 구분할 수 있게 updateParam 객체 도입하는거 어떤가요?

```kotlin
data class UpdateParam<T>(
    val value: T?,
)

fun <T> T?.toUpdateParam() = UpdateParam(this)
```

```kotlin
    fun update(
        height: UpdateParam<out Height>?,
        animalType: UpdateParam<out AnimalType>?,
        avatar: UpdateParam<out Url>?,
    ): User {
        return copy(
            height = if (height == null) this.height else height.value,
            animalType = if (animalType == null) this.animalType else animalType.value,
            avatar = if (avatar == null) this.avatar else avatar.value,
        )
    }
```

```kotlin
fun main() {
    val user = User.create(
        nickname = Nickname("nickname"),
        email = Email("email"),
        gender = Gender.MAN,
        mbti = Mbti("entp"),
        birthYear = BirthYear(1999),
        universityId = UUID.randomUUID(),
        majorId = UUID.randomUUID(),
    )

    user.update(
        height = Height(180).toUpdateParam(),
        animalType = AnimalType.CAT.toUpdateParam(),
        avatar = UpdateParam(null)
    )
}
```

2024-02-05 01:25 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
> +            height = if (height == null) this.height else height.value,
p3) 이쪽도 updateParam의 메서드로 만들고 oldbie(기존값)을 받아서 newbie(새로운값)을 만들어주면 깔끔할 거 같은데 어떠세요?

2024-02-05 01:25 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
> +        height: UpdateParam<out Height>?,
p3) out 필요한가요?!

2024-02-05 01:28 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserDomainServiceImpl.kt
> +        height: UpdateParam<out Height>?,
이거는 잘못사용했네요 Height?으로 고쳤어용

2024-02-05 02:04 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/entity/User.kt
> +            avatar = avatar,
객체 도입은 괜찮은데 클라이언트에게 어떻게 전달 받을지가 고민이었어요!

2024-02-05 02:56 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSetMyHeightUseCase.kt
> +    fun invoke(height: Height?)
p4) 키에 대한 nullable한 update는 없앨까요? 어때요?

2024-02-05 02:56 UTC, dojinyou commented on support/common/src/main/kotlin/com/studentcenter/weave/support/common/vo/UpdateParam.kt
> +}
p3) oldbiew만 받아도 newbie는 자기가 알고 있어서 괜찮을 것 같아요!
UpdateValue를 가져오는 느낌이라 이름도 바꾸면 좋을 것 같네요

```suggestion
fun <T> UpdateParam<T>?.getUpdateValue(oldValue: T?): T? {
    return if(this == null) oldValue else this.value
}
```

2024-02-05 02:57 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSetMyHeightUseCase.kt
> +    fun invoke(height: Height?)
코멘트 다는 중인데 적용 ㄷㄷㄷ

2024-02-05 02:59 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/user/port/inbound/UserSetMyHeightUseCase.kt
> +    fun invoke(height: Height?)
ㅋㅋㅋㅋ

2024-02-05 03:55 UTC, dojinyou approved these changes

2024-02-05 04:05 UTC, merged