[WEAV-178] 실 관련 기능 추가
Student-Center/weave-server pull request #61
Opened 2024-02-06 09:44 UTC by waterfogSW

## 구현사항
- 실 도메인 서비스 구현
- 키 입력시 실 획득(30 실)
  - null에서 변경되는 경우에만 실 획득(첫입력 케이스) 
- 닮은 동물상 입력시 실 획득(30 실)
  - null에서 변경되는 경우에만 실 획득(첫입력 케이스) 
- user_sil 엔티티 DDL user_id unique처리 안되어있던 부분 수정

2024-02-06 10:00 UTC, dojinyou reviewed
sil쪽 요거 히스토리는 안 만들어도 될까요?

2024-02-06 10:37 UTC, waterfogSW commented
> sil쪽 요거 히스토리는 안 만들어도 될까요?

음... 사용히스토리? 언제 필요할까요

2024-02-06 10:59 UTC, dojinyou requested changes
사용자한테 포인트 쌓인 이력이나 쓴 이력을 보여줘야된다고 생각했는데 별로 필요 없을까요?

2024-02-06 10:59 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserSilDomainServiceImpl.kt
> +    }
p2) 일단 락을 안 걸면 동시 업데이트할 경우 유실일 될 수 있을 것 같아요!

2024-02-06 11:02 UTC, waterfogSW commented
> 사용자한테 포인트 쌓인 이력이나 쓴 이력을 보여줘야된다고 생각했는데 별로 필요 없을까요?

음 그러면 포인트 이력조회 까지 UI가 나와야 할것같은데 이것도 MVP라 보시는거죠?, 
제생각엔 본격적으로 결제 기능 나와서 요청할때마다 포인트 사용되고 결제해야하는 상황이면 필요할것 같은데, 지금 상태에서는 포인트가 단순히 키, 닮은 동물 등록시에 쌓이기만하고 사용처가 없어서요 지금상태에서는 필요없을것 같다는 판단이었어요

2024-02-07 02:31 UTC, dojinyou requested changes

2024-02-07 02:31 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/domain/impl/UserSilDomainServiceImpl.kt
> +    ): UserSil {
p4) void해도 괜찮을 것 같네요?

2024-02-07 02:31 UTC, dojinyou commented on infrastructure/persistence/src/main/resources/db/migration/V8__create_user_sil.sql
> -    index (user_id)
p2) 요렇게 말고 새로운 버전 추가하고 거기서 alter나 drop and add 가 좋아보여요!

2024-02-07 02:36 UTC, waterfogSW commented on infrastructure/persistence/src/main/resources/db/migration/V8__create_user_sil.sql
> -    index (user_id)
아직 개발서버 배포안해서 괜찮을거같아서요 변경 필수?

2024-02-07 04:13 UTC, dojinyou commented on infrastructure/persistence/src/main/resources/db/migration/V9__change_user_id_index_to_unique.sql
> +    ADD UNIQUE INDEX user_id_unique (user_id);
p3) index naming table_column_index(uindex) 어떤가요?
```suggestion
    ADD UNIQUE INDEX user_sil_user_id_uindex (user_id);
```

2024-02-07 04:13 UTC, dojinyou approved these changes

2024-02-07 04:13 UTC, merged