[WEAV-132] 애플 소셜 로그인 API 구현
Student-Center/weave-server pull request #69
Opened 2024-02-09 10:17 UTC by wonjunYou

애플 소셜 로그인 API 구현 완료했습니다. 

문서 숙지가 오래 걸렸고 코드는 전반적으로 산님이 구조 잡아두셔서 거즘 변경사항 없이 할 수 있었네요 😊😊

* Nickname의 경우에는 idTokenResolve해서 반환할 때, 빈 문자열 `""` 태워서 반환하는 방식으로 우선 적용했습니다!

2024-02-09 10:35 UTC, dojinyou requested changes

2024-02-09 10:35 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +    companion object {
p2) kotlin convertion에서 `compaion object`는 클래스 최하단에 위치합니다.

2024-02-09 10:35 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +            URL(this.openIdProperties.providers.getValue(SocialLoginProvider.APPLE).jwksUri)
p3) jwksUri는 동적으로 항상 조회해야 하는 이유가 있나요?
```suggestion
        val jwksUri =
            URL(this.openIdProperties.providers.getValue(SocialLoginProvider.APPLE).jwksUri)
```

2024-02-09 10:35 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
> +        require(value.length <= MAX_LENGTH) { "닉네임은 ${MAX_LENGTH}자 이하여야 합니다." }
p1) 여기가 수정되면 안될 것 같아요! nickname의 제약 조건이 변경되어서는 안됩니다

2024-02-09 10:43 UTC, waterfogSW requested changes

2024-02-09 10:43 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
> +class AppleOpenIdTokenResolveStrategyTest : DescribeSpec({
p3) `@DisplayName` 붙여주면 좋을것같아요 -> `@DisplayName` 없이는 테스트 제목이 패키지 경로로 나와서 파악하기 힘들더라구요

2024-02-09 10:43 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
> +}
```suggestion
}

```

p1) EOF

2024-02-09 10:43 UTC, waterfogSW commented on application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/OpenIdPropertiesFixtureFactory.kt
> +            providerType : String,
p3) 여기서 String 쓰지말고 SocialLoginProvider쓰면 안되나요?

2024-02-09 10:43 UTC, waterfogSW commented on domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
> +})
p1) EOF 컨벤션 못지키는 부분이 자주 있는것 같아요, 별도로 커밋전 린트하는 githook을 만들거나 습관적으로 하시는게 좋을것같네요

2024-02-09 10:43 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
> +}
p3) companion object로 빼지말고 초기화 블럭 상단 (sut과 비슷한 위치?)에 두면 더 파악하기 좋을것 같은데 어떤가요?

2024-02-09 11:31 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +    companion object {
컨벤션 문서 정독하고 왔습니다! 자바랑 비슷할 줄 알고 스킵했었는데 생각보다 엄청 다르네요 ㅎㅎ..

2024-02-09 11:32 UTC, wonjunYou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
> +        require(value.length <= MAX_LENGTH) { "닉네임은 ${MAX_LENGTH}자 이하여야 합니다." }
헉 반영하겠습니다!!

2024-02-09 11:33 UTC, wonjunYou commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
> +class AppleOpenIdTokenResolveStrategyTest : DescribeSpec({
도진님 PR에서 말씀해 주셨었죠!! 추가하겠습니다 :)

2024-02-09 11:34 UTC, wonjunYou commented on application/src/testFixtures/kotlin/com/studentcenter/weave/application/common/properties/OpenIdPropertiesFixtureFactory.kt
> +            providerType : String,
오 좋은 생각이십니다!

2024-02-09 11:34 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
> +        require(value.length <= MAX_LENGTH) { "닉네임은 ${MAX_LENGTH}자 이하여야 합니다." }
애플 소셜로그인에 닉네임이 없나요? 없으면 어떻게 처리할 계획이실까요

2024-02-09 11:35 UTC, waterfogSW commented on domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
> +})
EOF에 한해서는 별도 intellij 설정도 존재합니다

2024-02-09 11:35 UTC, wonjunYou commented on domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
> +})
헉 두번이나 미스를,, 다음 PR부터는 꼭 습관 들여올게요😂

2024-02-09 11:40 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +            URL(this.openIdProperties.providers.getValue(SocialLoginProvider.APPLE).jwksUri)
생각해 보니 어차피 URI가 변할 일은 없겠군요

2024-02-09 11:47 UTC, wonjunYou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
> +        require(value.length <= MAX_LENGTH) { "닉네임은 ${MAX_LENGTH}자 이하여야 합니다." }
@waterfogSW 네 ㅠㅠ 음 한 글자 선에서 임의 닉네임을 부여하는 건 어떨까요? 

어제 여쭤본 결과 닉네임이 요구사항 상 필수적이지는 않다고 하시던데,

`nullable` 하게 간다면 특정 소셜 로그인 방식에 따라 닉네임 검증 여부가 나뉘는 것 같아서 아쉬운 것 같아요

2024-02-09 11:48 UTC, wonjunYou commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
> +}
`const val` 대신에 일반 `val`로 관리하자는 말씀이실까요?

2024-02-09 11:51 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +            URL(this.openIdProperties.providers.getValue(SocialLoginProvider.APPLE).jwksUri)
> 생각해 보니 어차피 URI가 변할 일은 없겠군요

어떻게 처리하실 계획이신가요? 🤔

2024-02-09 11:53 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
> +        require(value.length <= MAX_LENGTH) { "닉네임은 ${MAX_LENGTH}자 이하여야 합니다." }
필수적이지는 않다면 email 앞부분만 따서 nickname으로 가져오는것도 한 방법일것같네요

2024-02-09 11:55 UTC, wonjunYou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +            URL(this.openIdProperties.providers.getValue(SocialLoginProvider.APPLE).jwksUri)
> 어떻게 처리하실 계획이신가요? 🤔

각 클래스 내에 상수로 관리하는 것이 적합하지 않을까요.!!

2024-02-09 11:55 UTC, waterfogSW commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
> +}
네 그냥 취향차이긴 한것같아요

2024-02-09 11:57 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +            URL(this.openIdProperties.providers.getValue(SocialLoginProvider.APPLE).jwksUri)
provider측에서 jwks uri 를 변경하면 코드도 변경될것같아서 별도 properties 로 변경했어요, 저는 이게 db connection uri랑 다를바 없다생각해요

2024-02-09 13:51 UTC, wonjunYou commented
📌 리뷰 반영하여 이메일 `@` 앞부분을 닉네임으로 사용하는 방식으로 변경했습니다.

2024-02-09 14:11 UTC, waterfogSW approved these changes
도진님 approve도 받으시면 좋을거같아요 👍🏼

2024-02-09 14:11 UTC, waterfogSW commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
>  }
p4) 여기는 왜 변경이 있었나요?

2024-02-09 14:11 UTC, waterfogSW commented on domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
> +class NicknameTest : FunSpec ({
p4) DisplayName

2024-02-09 14:11 UTC, waterfogSW commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +        val result: JwtClaims = JwtTokenProvider.verifyJwksBasedToken(idToken, jwksUri).getOrThrow()
p5) getOrThrow() 저도 실수를 자주해서요, 제코드도 비판적으로 봐주시면 좋을것 같아요 👍

2024-02-09 14:11 UTC, waterfogSW commented on domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
> +    test("최소 글자수 기준보다 짧은 길이의 닉네임을 생성하는 경우, 에러가 발생한다.") {
p4) 최소글자수 최대글자수가 정확히 몇개인지 확인할 수 있었으면 좋겠네요
최소 글자수(1) 보다 짧으면 ~

2024-02-10 00:03 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +        val result: JwtClaims = JwtTokenProvider.verifyJwksBasedToken(idToken, jwksUri).getOrThrow()
사실 여기서도 customException을 띄워도 좋을 것 같아요.

2024-02-10 00:15 UTC, dojinyou approved these changes

2024-02-10 00:15 UTC, dojinyou commented on application/src/main/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategy.kt
> +    }
p4) 재활용될 여지가 적고 메서드 내용 자체가 직관적이라 굳이 분리 안해도 괜찮을 것 같아요
```suggestion
        val nickname: String = email.substringBefore(emailDelimiter)

        return if (nickname.length <= Nickname.MAX_LENGTH) nickname
            else nickname.substring(0, Nickname.MAX_LENGTH)
    }
```

2024-02-10 00:15 UTC, dojinyou commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/application/UserSocialLoginApplicationServiceTest.kt
> +@DisplayName("UserSocialLoginApplicationService")
👍

2024-02-10 00:15 UTC, dojinyou commented on application/src/test/kotlin/com/studentcenter/weave/application/user/service/util/impl/strategy/AppleOpenIdTokenResolveStrategyTest.kt
> +            result.email.value shouldBe "test@test.com"
p4) 
닉네임에 대한 검증은 닉네임 추출 로직에 의존적이에요. 검증이 꼭 필요한지 고민해보면 좋을 것 같아요! (로직 바뀌면 변경되어야함.)
이메일에 대한 검증에서 상수를 사용해도 좋을 것 같아요. 변경 포인트가 2곳으로 보입니다.

2024-02-10 00:15 UTC, dojinyou commented on domain/src/main/kotlin/com/studentcenter/weave/domain/user/vo/Nickname.kt
> +        const val MAX_LENGTH = 10
p5) 불필요한 변경이긴한데 뭐 순서가 요것도 괜찮죠

2024-02-10 00:15 UTC, dojinyou commented on domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
> +            Nickname("닉".repeat(11))
p4) 최대값이 변경되면 테스트 관리에 리소스가 사용되지 않도록 관리되면 좋을 것 같아요
```suggestion
            Nickname("닉".repeat(Nickname.MAX_LENGTH + 1))
```

2024-02-10 00:15 UTC, dojinyou commented on domain/src/test/kotlin/com/studentcenter/weave/domain/user/vo/NicknameTest.kt
> +        exception.message shouldBe "닉네임은 ${Nickname.MIN_LENGTH}글자 이상 ${Nickname.MAX_LENGTH}자 이하여야 합니다."
p4) 메세지 검증도 변경에 취약한 요소 중 하나라 특정 에러 타입 검증 정도면 충분할 것 같아요. 메세지는 변경될 수 있으니

2024-02-10 10:33 UTC, merged