[WEAV-186] ses implement
Student-Center/weave-server pull request #71
Opened 2024-02-10 08:45 UTC by dojinyou

## 작업내용
- Spring mail을 활용하여 인증번호 이메일 전송 서비스 구현
	<img width="761" alt="image" src="https://github.com/Student-Center/weave-server/assets/61923768/5596643a-0fba-487d-8ea0-f8a574169592">

2024-02-10 11:05 UTC, wonjunYou approved these changes
얼렁 ses 이슈가 해결되었으면 좋겠네요! 고생하셨습니다 :)

2024-02-10 11:05 UTC, wonjunYou commented on support/mail/src/main/resources/mail-templates/email-verification-number.html
> +                                  시간이 지날 경우 인증 번호를 재전송 해주셔야 합니다.
p4) 개인적으로 재전송이라는 표현이 약간 부자연스럽게 느껴지는 것 같아요!

아래와 같은 텍스트는 어떨까요?!

- 시간이 지난 경우, 새로운 인증 번호를 요청 바랍니다.
- 시간이 지난 경우, 인증 번호를 새로 발급받아 주세요!

2024-02-10 11:22 UTC, waterfogSW requested changes

2024-02-10 11:22 UTC, waterfogSW commented on support/mail/src/main/kotlin/com/studentcenter/weave/support/mail/adaptor/VerificationMailService.kt
> +class VerificationNumberMailService(
p2) 
- interface가 별도로 필요할것같아요
- adapter패키지에 위치해있는데, service클래스인게 조금 헷갈리네요, 
현재 아키텍처에서 사용하는 adapter의 의미는 헥사고날 primary adapter, secondary adapter에 가까워서요

p3) support 모듈은 이름에 맞게 기술적 세부사항(단순 메일전송)만 존재하는 모듈이어야 한다고 생각해요. 근데 현재 구현의 경우 verification number라는 비즈니스성격의 내용이 들어가는것 같아서 조금 모호하네요, 차라리 애플리케이션의 outboundport에 EmailVerificationHandler 인터페이스를 만들고 infra hexagon에 mail 모듈을 만들어 구현하는건 어떤가요?

2024-02-10 11:23 UTC, waterfogSW commented on support/mail/src/main/kotlin/com/studentcenter/weave/support/mail/adaptor/VerificationMailService.kt
> +    fun send(to: Email, verificationNumber : String, expirationDuration: Duration) {
@wonjunYou p2 가있으면 approve 하시면 안될것같아요 :) 코드 리뷰 정책 참고해 주세요(https://www.notion.so/student-center/Git-Convention-750879b0113d48088e5a74bd4a4a9b74)

2024-02-10 11:25 UTC, wonjunYou commented on support/mail/src/main/kotlin/com/studentcenter/weave/support/mail/adaptor/VerificationMailService.kt
> +    fun send(to: Email, verificationNumber : String, expirationDuration: Duration) {
@waterfogSW 아하 확인했습니다 :)

2024-02-11 03:44 UTC, dojinyou commented on support/mail/src/main/kotlin/com/studentcenter/weave/support/mail/adaptor/VerificationMailService.kt
> +class VerificationNumberMailService(
infra쪽으로 mail을 다 옮기고 Mailer interface 정의 후 implement하는 식으로 구현했습니다

2024-02-11 03:45 UTC, waterfogSW approved these changes

2024-02-11 03:48 UTC, merged