[WEAV-200] 미팅 장소 리스트 조회 API 구현
Student-Center/weave-server pull request #90
Opened 2024-02-13 15:04 UTC by wonjunYou

### 구현사항
* 미팅 팀에서 설정 가능한 모든 Location enum 값(item, value) 들을 받아옵니다.

### 리뷰 포인트
* Location이 domain은 아니고 enum 클래스라 db 조회도 없다는 점을 감안해서 controller에서 Response를 만들어 바로 내리도록 구성했는데요, 해당 로직도 엄연히 비즈니스 로직이라고 봐야 할지 궁금합니다!

2024-02-13 15:19 UTC, dojinyou requested changes

2024-02-13 15:19 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        val value: String
p2) 클라이언트가 필요한 정보가 내려가야할 것 같아요. 저희가 어떤 이름으로 관리하는지는 중요하지 않은 정보 같습니다.
```suggestion
        val name: String,
        val isisCapitalArea: Boolean
```

2024-02-13 15:19 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/controller/MeetingTeamRestController.kt
> +        return MeetingTeamLocationResponse.of()
p4) 제 개인적인 의견은 서비스까지 안 만들어도 될 것 같긴해요

2024-02-13 15:19 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        }
p3) 매번 응답을 만드는 것보다 싱글톤 패턴으로 하나의 인스턴스를 만들고 조회하는 팩토리 메서드를 이용하는게 좋은 것 같아요.

```suggestion
        private lateinit var instance: MeetingTeamLocationResponse

        fun getInstance(): MeetingTeamLocationResponse {
            if (instance == null) {
                instance = MeetingTeamLocationResponse(
                    Location.entries.map {
                        MeetingTeamLocationDto(it.value, it.isCapitalArea)
                    }
                )
            }

            return instance
        }
```

2024-02-13 21:13 UTC, waterfogSW approved these changes
👨‍💻 IMO

2024-02-13 21:13 UTC, waterfogSW commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        fun of(): MeetingTeamLocationResponse {
p3) 파라미터가 없어서 of라는 함수 명이 부적절한것같아요

2024-02-14 10:17 UTC, wonjunYou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        val value: String
![image](https://github.com/Student-Center/weave-server/assets/59856002/30553b84-a80f-4810-9a73-5848179c6f39)
요부분 클라분들이 미팅 팀 생성 시에 저희가 관리하는 ENUM의 item명으로 입력을 하고 계셔서, 해당 정보 포함해서 응답 api 수정했습니다!

2024-02-14 10:22 UTC, waterfogSW approved these changes

2024-02-14 13:04 UTC, dojinyou requested changes

2024-02-14 13:04 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +            )
p2) 이러면 매 메서드 호출마다 객체를 새로 생성하고 바인딩하는 과정이 발생할 수 있어요! null check로 초기화가 1번만 되게 해주세요.

2024-02-14 13:04 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        val isCapitalArea: String
p3) value라는 용어는 너무 모호해보여서 DisplayName 같은 적절한 이름을 쓰면 좋겠네요.

2024-02-14 13:04 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        val isCapitalArea: String
p3) isCapitalArea가 String Type인 이유는 뭘까요?

2024-02-14 14:49 UTC, wonjunYou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        val isCapitalArea: String
앗 실수했네요 ㅎ..

2024-02-15 00:10 UTC, waterfogSW commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
> +    fun getMeetingTeamLocations(): MeetingTeamLocationResponse
p3) 
```suggestion
    fun getMeetingTeamLocations(): MeetingTeamGetLocationsResponse
```

2024-02-15 03:29 UTC, dojinyou approved these changes
수고 하셨습니다

2024-02-15 03:29 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/api/MeetingTeamApi.kt
> +
p4) 스페이스가 들어갔네요
```suggestion

```

2024-02-15 03:29 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        }
p4) 최근에 보다보니 코틀린에 lazyinit 말고 lazy 키워드를 이용해서 지연 초기화 및 val의 not null type이 가능하네요!
```suggestion
        private val instance by lazy {
            Location.entries.map {
                MeetingLocationsResponse.MeetingLocationDto(it.name, it.value, it.isCapitalArea)
            }
        }

        fun getInstance() = instance
```

2024-02-15 03:29 UTC, dojinyou commented on bootstrap/http/src/main/kotlin/com/studentcenter/weave/bootstrap/meeting/dto/MeetingTeamLocationResponse.kt
> +        val isCapitalArea: Boolean
p4) tailing comma 체크해주세요!
```suggestion
        val isCapitalArea: Boolean,
```

2024-02-15 07:05 UTC, merged